((last-sort-comparer . bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("org" 0 3
                                   (bmkp-full-record #1#))
                                 (annotation)
                                 (tags)
                                 (buffer-name . "org")
                                 (front-context-string . ".projectile\n  dr")
                                 (rear-context-string . "019-11-28 19:46 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 4)
                                 (time 24385 19884 899747 0)
                                 (created 24384 14802 857408 0)
                                 (position . 251)
                                 (filename . "~/workspace/org/")
                                 (dired-directory . "~/workspace/org/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #2=(#("tag_manager-tests.adb" 0 21
                                   (bmkp-full-record #2#))
                                 (filename . "~/workspace/ada_test_architectures/src/tests/tag_manager-tests.adb")
                                 (buffer-name . "tag_manager-tests.adb")
                                 (front-context-string . "pragma Ada_2012;")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 2)
                                 (time 24309 63278 529807 0)
                                 (created 24309 62442 593809 0)
                                 (position . 1))
                             #3=(#("emacs-custom.el" 0 15
                                   (bmkp-full-record #3#))
                                 (filename . "~/.emacs.d/emacs-custom.el")
                                 (buffer-name . "emacs-custom.el")
                                 (front-context-string . "(custom-set-vari")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 4)
                                 (time 24385 19278 961427 0)
                                 (created 24307 5122 42549 0)
                                 (position . 1))
                             #4=(#("agenda" 0 6
                                   (bmkp-full-record #4#))
                                 (filename . "~/workspace/org/agenda/agenda.org")
                                 (buffer-name . "agenda.org")
                                 (front-context-string . "* Tcl :transport")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24385 19210 478284 0)
                                 (created 24300 49675 376021 0)
                                 (position . 1))
                             #5=(#("Documents" 0 9
                                   (bmkp-full-record #5#))
                                 (buffer-name . "Documents")
                                 (front-context-string . "desktop.ini\n  -r")
                                 (rear-context-string . "402 03-17 13:32 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 2)
                                 (time 24385 19917 457929 0)
                                 (created 24272 65028 953353 0)
                                 (position . 182)
                                 (filename . "~/Documents/")
                                 (dired-directory . "~/Documents/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #6=(#("bookmarks" 0 9
                                   (bmkp-full-record #6#))
                                 (buffer-name . "bookmarks")
                                 (front-context-string . "bookmarks-dev.or")
                                 (rear-context-string . "005 04-15 16:35 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 18)
                                 (time 24385 19971 604471 0)
                                 (created 24259 59463 593554 0)
                                 (position . 386)
                                 (filename . "~/workspace/org/bookmarks/")
                                 (dired-directory . "~/workspace/org/bookmarks/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #7=(#("workspace" 0 9
                                   (bmkp-full-record #7#))
                                 (annotation)
                                 (tags)
                                 (buffer-name . "workspace")
                                 (front-context-string . "org\n  drw-rw-rw-")
                                 (rear-context-string . "020-08-13 19:51 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 5)
                                 (time 24385 19850 667662 0)
                                 (created 24384 14795 378335 0)
                                 (position . 1613)
                                 (filename . #8="c:/Users/jeremy/AppData/Roaming/workspace/")
                                 (dired-directory . #8#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #9=(#("init.el" 0 7
                                   (bmkp-full-record #9#))
                                 (filename . "~/.emacs.d/init.el")
                                 (buffer-name . "init.el")
                                 (front-context-string . ";; to startup em")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 13)
                                 (time 24385 19324 24799 0)
                                 (created 24048 63295 407623 0)
                                 (position . 1))
                             #10=(#12=#(".emacs.d" 0 8
                                        (bmkp-full-record #10#))
                                      (buffer-name . ".emacs.d")
                                      (front-context-string . "lisp\n  -rw-rw-rw")
                                      (rear-context-string . "192 12-11 11:03 ")
                                      (front-context-region-string)
                                      (rear-context-region-string)
                                      (visits . 3)
                                      (time 24385 19350 734264 0)
                                      (created 24048 63284 71081 0)
                                      (position . 567)
                                      (filename . "~/AppData/Roaming/.emacs.d/")
                                      (dired-directory . "~/AppData/Roaming/.emacs.d/")
                                      (dired-marked)
                                      (dired-switches . "-al")
                                      (dired-subdirs)
                                      (dired-hidden-dirs)
                                      (handler . bmkp-jump-dired)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #11="")
 (last-bmenu-title . #11#)
 (last-bmenu-bookmark . #12#)
 (last-specific-buffer . #11#)
 (last-specific-file . #11#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "c:/Users/jeremy/AppData/Roaming/.emacs.d/bmk.emacs"))
