((last-sort-comparer
  (bmkp-file-alpha-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("_BbvaTkGen__declarations.h" 0 26
                                   (bmkp-full-record #1#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/_BbvaTkGen__declarations.h")
                                 (position . 0)
                                 (created 24383 53693 170363 0))
                             #2=(#("BbvaTkGen__definitions.c" 0 24
                                   (bmkp-full-record #2#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/BbvaTkGen__definitions.c")
                                 (position . 0)
                                 (created 24383 53692 986181 0))
                             #3=(#("BbvaTkGenVerif__definitions.c" 0 29
                                   (bmkp-full-record #3#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/BbvaTkGenVerif__definitions.c")
                                 (position . 0)
                                 (created 24383 53692 734423 0))
                             #4=(#("BbvaTkGenVerif__declarations.h" 0 30
                                   (bmkp-full-record #4#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/BbvaTkGenVerif__declarations.h")
                                 (position . 0)
                                 (created 24383 53692 386344 0))
                             #5=(#("BbvaTkGenRun__definitions.c" 0 27
                                   (bmkp-full-record #5#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/BbvaTkGenRun__definitions.c")
                                 (position . 0)
                                 (created 24383 53692 153997 0))
                             #6=(#("BbvaTkGenRun__declarations.h" 0 28
                                   (bmkp-full-record #6#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaTkGen/BbvaTkGenRun__declarations.h")
                                 (position . 0)
                                 (created 24383 53691 865803 0))
                             #7=(#("BbvaKeyStoreVerif__definitions.c" 0 32
                                   (bmkp-full-record #7#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStoreVerif__definitions.c")
                                 (position . 1)
                                 (created 24383 48109 968541 0))
                             #8=(#("BbvaKeyStoreVerif__declarations.h" 0 33
                                   (bmkp-full-record #8#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStoreVerif__declarations.h")
                                 (position . 1)
                                 (created 24383 48109 811746 0))
                             #9=(#("BbvaKeyStoreRun__definitions.c" 0 30
                                   (bmkp-full-record #9#))
                                 (time 24383 53719 412214 0)
                                 (visits . 0)
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStoreRun__definitions.c")
                                 (position . 1)
                                 (created 24383 48109 726726 0))
                             #10=(#("BbvaKeyStoreRun__declarations.h" 0 31
                                    (bmkp-full-record #10#))
                                  (time 24383 53950 5117 0)
                                  (visits . 2)
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStoreRun__declarations.h")
                                  (position . 1)
                                  (created 24383 48109 644354 0))
                             #11=(#("BbvaKeyStore__definitions.c" 0 27
                                    (bmkp-full-record #11#))
                                  (time 24383 53618 987557 0)
                                  (visits . 0)
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStore__definitions.c")
                                  (position . 1)
                                  (created 24383 48109 564398 0))
                             #12=(#("BbvaKeyStore__declarations.h" 0 28
                                    (bmkp-full-record #12#))
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/BbvaKeyStore__declarations.h")
                                  (position . 1)
                                  (created 24383 48109 482101 0))
                             #13=(#("SUPTER-7682_mexique" 0 19
                                    (bmkp-full-record #13#))
                                  (buffer-name . "SUPTER-7682_mexique")
                                  (front-context-string . ".metadata\n  -rw-")
                                  (rear-context-string . "020-08-20 14:55 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24383 46455 980018 0)
                                  (created 24383 41967 653915 0)
                                  (position . 270)
                                  (filename . #14="c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/")
                                  (dired-directory . #14#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #15=(#("_BbvaKeyStore__declarations.h" 0 29
                                    (bmkp-full-record #15#))
                                  (annotation)
                                  (tags)
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/_BbvaKeyStore__declarations.h")
                                  (buffer-name . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/_BbvaKeyStore__declarations.h")
                                  (front-context-string . "// included by _")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time 24383 53727 415328 0)
                                  (created 24383 53727 415328 0)
                                  (position . 1))
                             #16=(#("SchemeSecrets.h" 0 15
                                    (bmkp-full-record #16#))
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/Ext/scheme_tools_private/Inc/SchemeSecrets.h")
                                  (buffer-name . "SchemeSecrets.h")
                                  (front-context-string . "/*!\n@verbatim\n--")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #17=(24362 46661 117882 0))
                                  (created . #17#)
                                  (position . 1))
                             #18=(#("notes_api2json.txt" 0 18
                                    (bmkp-full-record #18#))
                                  (annotation)
                                  (tags)
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/api2json/notes_api2json.txt")
                                  (buffer-name . "notes_api2json.txt")
                                  (front-context-string)
                                  (rear-context-string . "t to uint32\n\n** ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #19=(24258 16620 61676 0))
                                  (created . #19#)
                                  (position . 315))
                             #20=(#23=#("notes_ingenico.org" 0 18
                                        (bmkp-full-record #20#))
                                      (end-position . 5192)
                                      (filename . "~/workspace/org/ingenico/notes_ingenico.org")
                                      (buffer-name . "notes_ingenico.org")
                                      (front-context-string . "\n** CodeWarrior\n")
                                      (rear-context-string . "n= dans le PATH\n")
                                      (front-context-region-string)
                                      (rear-context-region-string)
                                      (visits . 8)
                                      (time 24383 50560 734614 0)
                                      (created 24234 61914 567933 0)
                                      (position . 5192))
                             #21=(#("ep2_lib_src" 0 11
                                    (bmkp-full-record #21#))
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTEL-13626_EP2/cmp_pack_security_EP2KeyExpRSA_T2/cmp_security_ep2keyexprsa_private/Src/Lib/EP2_KeyExpRSA.c")
                                  (buffer-name . "EP2_KeyExpRSA.c")
                                  (front-context-string . "    iBufferOffse")
                                  (rear-context-string . "ParamIAPP ) );\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 2)
                                  (time 24207 10532 108436 0)
                                  (created 24055 42948 239297 0)
                                  (position . 3689)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks
  #("_BbvaTkGen__declarations.h" 0 26
    (bmkp-full-record #1#))
  #("BbvaTkGen__definitions.c" 0 24
    (bmkp-full-record #2#))
  #("BbvaTkGenVerif__definitions.c" 0 29
    (bmkp-full-record #3#))
  #("BbvaTkGenVerif__declarations.h" 0 30
    (bmkp-full-record #4#))
  #("BbvaTkGenRun__definitions.c" 0 27
    (bmkp-full-record #5#))
  #("BbvaTkGenRun__declarations.h" 0 28
    (bmkp-full-record #6#))
  #("_BbvaKeyStore__declarations.h" 0 29
    (bmkp-full-record #15#))
  #("BbvaKeyStore__definitions.c" 0 27
    (bmkp-full-record #11#))
  #("BbvaKeyStore__declarations.h" 0 28
    (bmkp-full-record #12#))
  #("BbvaKeyStoreVerif__definitions.c" 0 32
    (bmkp-full-record #7#))
  #("BbvaKeyStoreVerif__declarations.h" 0 33
    (bmkp-full-record #8#))
  #("BbvaKeyStoreRun__definitions.c" 0 30
    (bmkp-full-record #9#))
  #("BbvaKeyStoreRun__declarations.h" 0 31
    (bmkp-full-record #10#)))
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #22="")
 (last-bmenu-title . #22#)
 (last-bmenu-bookmark . #23#)
 (last-specific-buffer . #22#)
 (last-specific-file . #22#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "c:/Users/jpiffret/AppData/Roaming/.emacs.d/bmk.ingenico")
 (last-previous-bookmark-file . "c:/Users/jpiffret/AppData/Roaming/.emacs.d/bmk.emacs"))
