((last-sort-comparer
  (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("_BbvaKeyStore__declarations.h" 0 29
                                   (bmkp-full-record #1#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/src/BbvaKeyStore/_BbvaKeyStore__declarations.h")
                                 (buffer-name . "_BbvaKeyStore__declarations.h")
                                 (front-context-string . "// included by _")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #2=(24383 40808 166708 0))
                                 (created . #2#)
                                 (position . 1))
                             #3=(#30=#(".bookmarks" 0 10
                                       (bmkp-full-record #3#))
                                     (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/.bookmarks")
                                     (buffer-name . ".bookmarks")
                                     (front-context-string)
                                     (rear-context-string)
                                     (front-context-region-string)
                                     (rear-context-region-string)
                                     (visits . 0)
                                     (time . #4=(24383 40771 192219 0))
                                     (created . #4#)
                                     (position . 1))
                             #5=(#("SchemeSecrets.h" 0 15
                                   (bmkp-full-record #5#))
                                 (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTER-7682_mexique/Ext/scheme_tools_private/Inc/SchemeSecrets.h")
                                 (buffer-name . "SchemeSecrets.h")
                                 (front-context-string . "/*!\n@verbatim\n--")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #6=(24362 46661 117882 0))
                                 (created . #6#)
                                 (position . 1))
                             #7=(#("org" 0 3
                                   (bmkp-full-record #7#))
                                 (buffer-name . "org")
                                 (front-context-string . "bookmarks\n  drwx")
                                 (rear-context-string . "192 07-07 13:01 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 3)
                                 (time 24383 39812 438862 0)
                                 (created 24325 36025 409919 0)
                                 (position . 237)
                                 (filename . #8="c:/Users/jpiffret/AppData/Roaming/workspace/org/")
                                 (dired-directory . #8#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #9=(#("tag_manager-tests.adb" 0 21
                                   (bmkp-full-record #9#))
                                 (filename . "~/workspace/ada_test_architectures/src/tests/tag_manager-tests.adb")
                                 (buffer-name . "tag_manager-tests.adb")
                                 (front-context-string . "pragma Ada_2012;")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 2)
                                 (time 24309 63278 529807 0)
                                 (created 24309 62442 593809 0)
                                 (position . 1))
                             #10=(#("emacs-custom.el" 0 15
                                    (bmkp-full-record #10#))
                                  (filename . "~/.emacs.d/emacs-custom.el")
                                  (buffer-name . "emacs-custom.el")
                                  (front-context-string . "(custom-set-vari")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 2)
                                  (time 24383 40024 677192 0)
                                  (created 24307 5122 42549 0)
                                  (position . 1))
                             #11=(#("agenda" 0 6
                                    (bmkp-full-record #11#))
                                  (filename . "~/workspace/org/agenda/agenda.org")
                                  (buffer-name . "agenda.org")
                                  (front-context-string . "* Tcl :transport")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #12=(24300 49675 376021 0))
                                  (created . #12#)
                                  (position . 1))
                             #13=(#("Documents" 0 9
                                    (bmkp-full-record #13#))
                                  (buffer-name . "Documents")
                                  (front-context-string . "desktop.ini\n  -r")
                                  (rear-context-string . "402 03-17 13:32 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #14=(24272 65028 953353 0))
                                  (created . #14#)
                                  (position . 182)
                                  (filename . #15="c:/Users/jpiffret/Documents/")
                                  (dired-directory . #15#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #16=(#("bookmarks" 0 9
                                    (bmkp-full-record #16#))
                                  (buffer-name . "bookmarks")
                                  (front-context-string . "bookmarks-dev.or")
                                  (rear-context-string . "005 04-15 16:35 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 8)
                                  (time 24362 29584 558918 0)
                                  (created 24259 59463 593554 0)
                                  (position . 386)
                                  (filename . #17="c:/Users/jpiffret/AppData/Roaming/workspace/org/bookmarks/")
                                  (dired-directory . #17#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #18=(#("notes_api2json.txt" 0 18
                                    (bmkp-full-record #18#))
                                  (annotation)
                                  (tags)
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/api2json/notes_api2json.txt")
                                  (buffer-name . "notes_api2json.txt")
                                  (front-context-string)
                                  (rear-context-string . "t to uint32\n\n** ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #19=(24258 16620 61676 0))
                                  (created . #19#)
                                  (position . 315))
                             #20=(#("notes_ingenico.org" 0 18
                                    (bmkp-full-record #20#))
                                  (end-position . 5192)
                                  (filename . "~/workspace/org/ingenico/notes_ingenico.org")
                                  (buffer-name . "notes_ingenico.org")
                                  (front-context-string . "\n** CodeWarrior\n")
                                  (rear-context-string . "n= dans le PATH\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 7)
                                  (time 24323 3824 891571 0)
                                  (created 24234 61914 567933 0)
                                  (position . 5192))
                             #21=(#("Ingenico_Workspace" 0 18
                                    (bmkp-full-record #21#))
                                  (buffer-name . "Ingenico_Workspace")
                                  (front-context-string . "archives\n  drwxr")
                                  (rear-context-string . "096 12-12 16:44 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 14)
                                  (time 24383 39679 473922 0)
                                  (created 24215 7787 555288 0)
                                  (position . 199)
                                  (filename . #22="c:/Users/jpiffret/Ingenico_Workspace/")
                                  (dired-directory . #22#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #23=(#("workspace" 0 9
                                    (bmkp-full-record #23#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "workspace")
                                  (front-context-string)
                                  (rear-context-string . "096 04-15 16:35 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 10)
                                  (time 24362 30807 788401 0)
                                  (created 24234 47836 757673 0)
                                  (position . 190)
                                  (filename . #24="c:/Users/jpiffret/AppData/Roaming/workspace/")
                                  (dired-directory . #24#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #25=(#("ep2_lib_src" 0 11
                                    (bmkp-full-record #25#))
                                  (filename . "c:/Users/jpiffret/Ingenico_Workspace/SUPTEL-13626_EP2/cmp_pack_security_EP2KeyExpRSA_T2/cmp_security_ep2keyexprsa_private/Src/Lib/EP2_KeyExpRSA.c")
                                  (buffer-name . "EP2_KeyExpRSA.c")
                                  (front-context-string . "    iBufferOffse")
                                  (rear-context-string . "ParamIAPP ) );\n\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 2)
                                  (time 24207 10532 108436 0)
                                  (created 24055 42948 239297 0)
                                  (position . 3689))
                             #26=(#("init.el" 0 7
                                    (bmkp-full-record #26#))
                                  (filename . "~/.emacs.d/init.el")
                                  (buffer-name . "init.el")
                                  (front-context-string . ";; to startup em")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 8)
                                  (time 24383 40671 674129 0)
                                  (created 24048 63295 407623 0)
                                  (position . 1))
                             #27=(#(".emacs.d" 0 8
                                    (bmkp-full-record #27#))
                                  (buffer-name . ".emacs.d")
                                  (front-context-string . "lisp\n  -rw-rw-rw")
                                  (rear-context-string . "192 12-11 11:03 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24048 63830 175951 0)
                                  (created 24048 63284 71081 0)
                                  (position . 567)
                                  (filename . #28="c:/Users/jpiffret/AppData/Roaming/.emacs.d/")
                                  (dired-directory . #28#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #29="")
 (last-bmenu-title . #29#)
 (last-bmenu-bookmark . #30#)
 (last-specific-buffer . #29#)
 (last-specific-file . #29#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "c:/Users/jpiffret/AppData/Roaming/.emacs.d/bmk.emacs")
 (last-previous-bookmark-file . "c:/Users/jpiffret/AppData/Roaming/.emacs.d/bookmarks"))
