((last-sort-comparer
  (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("birdz-dev-home" 0 14
                                   (bmkp-full-record #1#))
                                 (buffer-name . "jeremy.piffret</plinkx:dev:>")
                                 (front-context-string . "dev\n  drwx------")
                                 (rear-context-string . "96 Oct 27 14:01 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24472 15411 878044 0)
                                 (created 24472 15341 518261 0)
                                 (position . 672)
                                 (filename . "/plinkx:dev:/home/jeremy.piffret/")
                                 (dired-directory . "/plinkx:dev:/home/jeremy.piffret/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             ("birdz-bdd-home"
                              (buffer-name . "jeremy.piffret</plinkx:bdd:>")
                              (front-context-string . ".bash_history\n  ")
                              (rear-context-string . "06 Oct 27 16:24 ")
                              (front-context-region-string)
                              (rear-context-region-string)
                              (visits . 0)
                              (time 24472 15311 582761 0)
                              (created 24472 15311 582761 0)
                              (position . 281)
                              (filename . "/plinkx:bdd:/home/jeremy.piffret/")
                              (dired-directory . "/plinkx:bdd:/home/jeremy.piffret/")
                              (dired-marked)
                              (dired-switches . "-al")
                              (dired-subdirs)
                              (dired-hidden-dirs)
                              (handler . bmkp-jump-dired))
                             #2=(#("plink-dev" 0 9
                                   (bmkp-full-record #2#))
                                 (buffer-name . "dev")
                                 (front-context-string . "crplus\n  -rw-rw-")
                                 (rear-context-string . "96 Oct 23 10:56 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 2)
                                 (time 24472 15338 493843 0)
                                 (created 24471 65454 419224 0)
                                 (position . 296)
                                 (filename . "/plinkx:dev:/home/jeremy.piffret/dev/")
                                 (dired-directory . "/plinkx:dev:/home/jeremy.piffret/dev/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #3="")
 (last-bmenu-title . #3#)
 (last-bmenu-bookmark)
 (last-specific-buffer . #3#)
 (last-specific-file . #3#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "c:/Users/jeremy.piffret.ext/AppData/Roaming/.emacs.d/emacs-bookmarks/bmk.birdz")
 (last-previous-bookmark-file . "c:/Users/jeremy.piffret.ext/AppData/Roaming/.emacs.d/emacs-bookmarks/bmk.emacs"))
