((last-sort-comparer
  (bmkp-info-node-name-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist #1=(#("birdz-bdd-server-jeremy.piffret" 0 31
                                   (bmkp-full-record #1#))
                                 (buffer-name . "jeremy.piffret<bdd>")
                                 (front-context-string . ".bash_history\n  ")
                                 (rear-context-string . "80 Oct 19 15:32 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time 24461 38246 647520 0)
                                 (created 24461 38246 647520 0)
                                 (position . 281)
                                 (filename . "/plinkx:bdd:/home/jeremy.piffret/")
                                 (dired-directory . "/plinkx:bdd:/home/jeremy.piffret/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #2=(#("birdz-dev-server-jeremy.piffret" 0 31
                                   (bmkp-full-record #2#))
                                 (buffer-name . "jeremy.piffret<dev>")
                                 (front-context-string . ".bash_history\n  ")
                                 (rear-context-string . "43 Oct 19 15:25 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 2)
                                 (time 24461 43302 901579 0)
                                 (created 24461 37868 794811 0)
                                 (position . 279)
                                 (filename . "/plinkx:dev:/home/jeremy.piffret/")
                                 (dired-directory . "/plinkx:dev:/home/jeremy.piffret/")
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #3=(#("birdz.ssh" 0 9
                                   (bmkp-full-record #3#))
                                 (buffer-name . ".ssh")
                                 (front-context-string . ":\n  total used i")
                                 (rear-context-string . "piffret.ext/.ssh")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #4=(24461 37046 614964 0))
                                 (created . #4#)
                                 (position . 35)
                                 (filename . #5="c:/Users/jeremy.piffret.ext/.ssh/")
                                 (dired-directory . #5#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #6=(#("notes_birdz.org.txt" 0 19
                                   (bmkp-full-record #6#))
                                 (filename . "~/.emacs.d/notes_birdz.org.txt")
                                 (buffer-name . "notes_birdz.org.txt")
                                 (front-context-string . "* compte : jerem")
                                 (rear-context-string)
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 1)
                                 (time 24461 38084 871535 0)
                                 (created 24461 36510 474077 0)
                                 (position . 1))
                             #7=(#("download" 0 8
                                   (bmkp-full-record #7#))
                                 (buffer-name . "download")
                                 (front-context-string . "ada\n  -rw-rw-rw-")
                                 (rear-context-string . "96 Sep  4  2019 ")
                                 (front-context-region-string)
                                 (rear-context-region-string)
                                 (visits . 0)
                                 (time . #8=(24416 60523 618805 0))
                                 (created . #8#)
                                 (position . 253)
                                 (filename . #9="e:/download/")
                                 (dired-directory . #9#)
                                 (dired-marked)
                                 (dired-switches . "-al")
                                 (dired-subdirs)
                                 (dired-hidden-dirs)
                                 (handler . bmkp-jump-dired))
                             #10=(#("README.org" 0 10
                                    (bmkp-full-record #10#))
                                  (filename . "~/.emacs.d/README.org")
                                  (buffer-name . "README.org")
                                  (front-context-string . "#+TITLE: My Lite")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 4)
                                  (time 24461 37313 448621 0)
                                  (created 24398 7434 345489 0)
                                  (position . 1))
                             #11=(#("init.org" 0 8
                                    (bmkp-full-record #11#))
                                  (filename . "~/.emacs.d/README.org")
                                  (buffer-name . "README.org")
                                  (front-context-string)
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 3)
                                  (time 24461 43623 524690 0)
                                  (created 24390 13718 416714 0)
                                  (position . 1))
                             #12=(#("org" 0 3
                                    (bmkp-full-record #12#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "org")
                                  (front-context-string . ".projectile\n  dr")
                                  (rear-context-string . "019-11-28 19:46 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 4)
                                  (time 24385 19884 899747 0)
                                  (created 24384 14802 857408 0)
                                  (position . 251)
                                  (filename . "~/workspace/org/")
                                  (dired-directory . "~/workspace/org/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #13=(#28=#("emacs-custom.el" 0 15
                                        (bmkp-full-record #13#))
                                      (filename . "~/.emacs.d/emacs-custom.el")
                                      (buffer-name . "emacs-custom.el")
                                      (front-context-string . "(custom-set-vari")
                                      (rear-context-string)
                                      (front-context-region-string)
                                      (rear-context-region-string)
                                      (visits . 6)
                                      (time 24428 43193 979751 0)
                                      (created 24307 5122 42549 0)
                                      (position . 1))
                             #14=(#("agenda" 0 6
                                    (bmkp-full-record #14#))
                                  (filename . "~/workspace/org/agenda/agenda.org")
                                  (buffer-name . "agenda.org")
                                  (front-context-string . "* Tcl :transport")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24385 19210 478284 0)
                                  (created 24300 49675 376021 0)
                                  (position . 1))
                             #15=(#("Documents" 0 9
                                    (bmkp-full-record #15#))
                                  (buffer-name . "Documents")
                                  (front-context-string . "desktop.ini\n  -r")
                                  (rear-context-string . "402 03-17 13:32 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 2)
                                  (time 24385 19917 457929 0)
                                  (created 24272 65028 953353 0)
                                  (position . 182)
                                  (filename . "~/Documents/")
                                  (dired-directory . "~/Documents/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #16=(#("bookmarks" 0 9
                                    (bmkp-full-record #16#))
                                  (buffer-name . "bookmarks")
                                  (front-context-string . "bookmarks-dev.or")
                                  (rear-context-string . "005 04-15 16:35 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 28)
                                  (time 24416 62975 630177 0)
                                  (created 24259 59463 593554 0)
                                  (position . 386)
                                  (filename . "~/workspace/org/bookmarks/")
                                  (dired-directory . "~/workspace/org/bookmarks/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #17=(#("workspace" 0 9
                                    (bmkp-full-record #17#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . "workspace")
                                  (front-context-string . "org\n  drw-rw-rw-")
                                  (rear-context-string . "020-08-13 19:51 ")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 9)
                                  (time 24390 9942 668926 0)
                                  (created 24384 14795 378335 0)
                                  (position . 1613)
                                  (filename . "~/workspace/")
                                  (dired-directory . "~/workspace/")
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #18=(#("init.el" 0 7
                                    (bmkp-full-record #18#))
                                  (filename . "~/.emacs.d/init.el")
                                  (buffer-name . "init.el")
                                  (front-context-string . ";; to startup em")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 16)
                                  (time 24398 7396 83529 0)
                                  (created 24048 63295 407623 0)
                                  (position . 1))
                             #19=(#(".emacs.d" 0 8
                                    (bmkp-full-record #19#))
                                  (annotation)
                                  (tags)
                                  (buffer-name . ".emacs.d")
                                  (front-context-string . "\n  total used in")
                                  (rear-context-string . "oaming/.emacs.d:")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 0)
                                  (time . #20=(24461 43628 261774 0))
                                  (created . #20#)
                                  (position . 56)
                                  (filename . #21="c:/Users/jeremy.piffret.ext/AppData/Roaming/.emacs.d/")
                                  (dired-directory . #21#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #22=(#("generator" 0 9
                                    (bmkp-full-record #22#))
                                  (tags "ingenico")
                                  (buffer-name . "GenDllSch")
                                  (front-context-string . "generator/GenDll")
                                  (rear-context-string . "orkspace/scheme_")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24387 36868 935019 0)
                                  (created 24387 36865 701396 0)
                                  (position . 63)
                                  (filename . #23="c:/Users/jpiffret/AppData/Roaming/Ingenico_Workspace/scheme_generator/GenDllSch/")
                                  (dired-directory . #23#)
                                  (dired-marked)
                                  (dired-switches . "-al")
                                  (dired-subdirs)
                                  (dired-hidden-dirs)
                                  (handler . bmkp-jump-dired))
                             #24=(#("Ingenico_Workspace" 0 18
                                    (bmkp-full-record #24#))
                                  (end-position . 1076)
                                  (time 24428 39093 882925 0)
                                  (visits . 4)
                                  (tags "ingenico")
                                  (filename . "~/Ingenico_Workspace/")
                                  (front-context-string . "SUPTER-7682_mexi")
                                  (rear-context-string . "92 Aug 26 11:33 ")
                                  (position . 1076))
                             #25=(#("SchemeSecrets.h" 0 15
                                    (bmkp-full-record #25#))
                                  (filename . "~/Ingenico_Workspace/SUPTER-7682_mexique/Ext/scheme_tools_private/Inc/SchemeSecrets.h")
                                  (buffer-name . "SchemeSecrets.h")
                                  (front-context-string . "/*!\n@verbatim\n--")
                                  (rear-context-string)
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 1)
                                  (time 24383 54887 359067 0)
                                  (created 24362 46661 117882 0)
                                  (position . 1))
                             #26=(#("notes_ingenico.org" 0 18
                                    (bmkp-full-record #26#))
                                  (tags "ingenico")
                                  (end-position . 5192)
                                  (filename . "~/workspace/org/ingenico/notes_ingenico.org")
                                  (buffer-name . "notes_ingenico.org")
                                  (front-context-string . "\n** CodeWarrior\n")
                                  (rear-context-string . "n= dans le PATH\n")
                                  (front-context-region-string)
                                  (rear-context-region-string)
                                  (visits . 9)
                                  (time 24399 44006 36630 0)
                                  (created 24234 61914 567933 0)
                                  (position . 5192)))
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks)
 (last-bmenu-filter-function)
 (last-bmenu-filter-pattern . #27="")
 (last-bmenu-title . #27#)
 (last-bmenu-bookmark . #28#)
 (last-specific-buffer . #27#)
 (last-specific-file . #27#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "c:/Users/jeremy.piffret.ext/AppData/Roaming/.emacs.d/emacs-bookmarks/bmk.emacs")
 (last-previous-bookmark-file . "c:/Users/jeremy.piffret.ext/AppData/Roaming/.emacs.d/emacs-bookmarks/bmk.emacs"))
